<?php

/**
 * @file
 * Contains eba.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\eba\Helpers\EbaConfig;

/**
 * Implements hook_help().
 */
function eba_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eba module.
    case 'help.page.eba':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Attach a block to an entity bundle') . '</p>';
      return $output;

    default:
  }
}

// change all this to use https://www.drupal.org/node/2287827
